# Generated by Django 5.1.2 on 2025-05-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='date',
        ),
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
    ]
