# Generated by Django 5.1.2 on 2025-05-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_date_remove_bid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('toys', 'Toys'), ('books', 'Books'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, default='default.png', upload_to='medai/'),
        ),
    ]
