# Generated by Django 5.1.2 on 2025-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://openclipart.org/image/400px/346569'),
        ),
    ]
